* 7.1-7.4 + 10.2
A) wie zijn 'De grote drie'?
   - Churchill van engeland
   - roosevelt van de VS
   - Stalin van de USSR
B) De conferentie van Potsdam
   a) Waneer was de conferentie van potsdam
      - een paar maanden na de capitulatie van Duitsland
   b) Wat waren de berijkte overeenkomsten
      - Oorlogsmisdadigers moeten bestraft worden
      - de grens tussen duitsland en Polen moet verder tot het westen opgeschoven worden
      - de Duitstalige minderheden uit Polen Tjecho-slowakije en Hongarije moeten terug naar Duitsland
      - Duitsland moet een economische eenheid blijven
      - er moet een vredesverdrag voor heel duitsland moeten worden voorberijd
C) Wat waren het west- en oostblok
   - het waren de westerse en sovjet invloedsferen
D) Wat was het ijzeren gordijn
   - het ijzeren gordijn was de grens tussen het westblok en het oostblok
E) Wat was de Truman-Doctrine
   - een toespraak waarin Harry Truman zij dat de VS hulp zou bieden aan landen die dreigde communistisch te worden
F) Wanneer werden de BRD en DDR weer een
   - in 1990
G) Wanneer overleed Stalin
   - in 1953
H) Wie verving stalin en waneer
   - nikita Chroesjtsjov
   - 1953
I) wat was een van de gevolgen van de uitlekking van de speech van Stalins vervanger
   - DeStalinisatie
   - De hongaarse opstand
     (Indirect) de Praagse lente
J) Wat was het Marshallplan en wat waren de voorwaarden
   - was een plan van de VS om europa te helpen terug te komen van de oorlog en zo de communisten uit west-europa te houde
   - de eu oprichten en niet communisten te worde
K) Welke landen waren de eerste leden van de EGKS
   - Frankrijk
   - West-Duitsland
   - Italie
   - BeNeLux
L) Wat was het verdrag van Rome
   - Een verdrag tussen Frankrijk en Duitsland om hun concurentie te verminderen
M) Waarom was er in de jaren 80 een economische crisis in de Sovjet-Unie
   - 
N) In welk jaar kwam Gorbatsjov aan de macht, wat wilde hij doen en hoe?
   - 1985
   - de Sovjet economie helen door in kleine schaal de vrijemarktseconomie toe te staan
O) Het oostblok valt uit een, leg uit
   -
P) Waneer viel de muur
   - 1989
Q) Wat ging er mis met gorbatsjov's plan?
   - Door de vrije markt stegen de prijzen van goederen enorm, maar de lonen bleven laag.
R) Welke gevolgen hadden "glasnost" en "perestrojka"
   - Glasnost veroorzaakte politieke crisis
   -perestrojka veroorzaakte
A )  Wat was de eerste deelstaat om onafhankelijk te worden?
   - 
