* Verantwoording gedichten
** Serieuzer gedicht (Engelse stijl)
*** Tekst
De tekst voor het serieuzere gedicht gaat over de reis van het hoofdpersoon, eerst heeft hij geen idee hoe slecht de wereld waarin hij leeft is, vervolgens leert hij het en maakt hij een plan, hij denkt dat hij klaar is. Hij is natuurlijk niet zo. Hij probeerde nog 2 keer te ontsnappen voordat het hem lukt.
*** Vormgeving
De vormgeving voor het serieuzere gedicht heb ik als volgt gemaakt: De achtergrond is gemaakt door een ai met de prompt: "A man in a dystopian factory full of futuristic machines, looking at a sunrise, digital art, futuristic machines with many displays and a creepy feeling, the window the man is looking throug has bars" In het midden is het plaatje wat donkerder gemaakt en een beetje vervaagd zodat de tekst leesbaarder is. Het lettertype is gekozen omdat het goed leesbaar is en er serieus genoeg uitzag het is ook prima leesbaar. De tekst heeft de letters en zinnen wat verder uit elkaar gezet zodat het beter in het vakje past.
** Lichter gedicht (Nederlandse stijl)
*** Tekst
De tekst in het lichtere gedicht gaat over dezelfde gebeurtenissen het hoofdpersoon zit vast in een dystopische stad en probeert te ontsnappen maar wordt gepakt en het land uit gestuurt als slaaf, maar de beveiliging aan de andere kant is zo goed als nul dus ontsnapt hij en is hij blij 😄
*** Vormgeving
Voor het lichtere gedicht heb ik gewoon een plaatje van het internet gepakt omdat het er grappiger en lichter uitzag dan een plaatje van het AI. ik heb het midden een beetje groen gekleurd zodat de tekst beter leesbaar is, het font is gekozen omdat het er grappig uitzag en goed paste, de kleur is gewoon zwart omdat het goed leesbaar is en een beetje lijkt op de spreuk tegels die je wel eens ziet.
